<<<<<<< HEAD
<#assign UserRoleType=statics["com.sinochem.yunlian.upm.admin.constant.UserRoleType"]>
<#assign SMSStatus=statics["com.sinochem.yunlian.upm.admin.constant.SMSStatus"]>
<#assign RoleStatus=statics["com.sinochem.yunlian.upm.admin.constant.RoleStatus"]>
<#assign UserRoleSourceType=statics["com.sinochem.yunlian.upm.admin.constant.UserRoleSourceType"]>
<#assign ContextAttrType=statics["com.sinochem.yunlian.upm.admin.constant.ContextAttrType"]>
<#assign UserType=statics["com.sinochem.yunlian.upm.admin.constant.UserType"]>
<#assign MenuStatus=statics["com.sinochem.yunlian.upm.admin.constant.MenuStatus"]>
<#assign RolePermissionRltStatus=statics["com.sinochem.yunlian.upm.admin.constant.RolePermissionRltStatus"]>
<#assign CommonStatus=statics["com.sinochem.yunlian.upm.admin.constant.CommonStatus"]>
<#assign UserStatus=statics["com.sinochem.yunlian.upm.admin.constant.UserStatus"]>
<#assign MenuType=statics["com.sinochem.yunlian.upm.admin.constant.MenuType"]>
=======
<#assign UserType=statics["com.sinochem.yunlian.upm.admin.constant.UserType"]>
<#assign RoleStatus=statics["com.sinochem.yunlian.upm.admin.constant.RoleStatus"]>
<#assign UserStatus=statics["com.sinochem.yunlian.upm.admin.constant.UserStatus"]>
<#assign SMSStatus=statics["com.sinochem.yunlian.upm.admin.constant.SMSStatus"]>
<#assign MenuStatus=statics["com.sinochem.yunlian.upm.admin.constant.MenuStatus"]>
<#assign ContextAttrType=statics["com.sinochem.yunlian.upm.admin.constant.ContextAttrType"]>
<#assign RolePermissionRltStatus=statics["com.sinochem.yunlian.upm.admin.constant.RolePermissionRltStatus"]>
<#assign CommonStatus=statics["com.sinochem.yunlian.upm.admin.constant.CommonStatus"]>
<#assign UserRoleType=statics["com.sinochem.yunlian.upm.admin.constant.UserRoleType"]>
<#assign MenuType=statics["com.sinochem.yunlian.upm.admin.constant.MenuType"]>
<#assign UserRoleSourceType=statics["com.sinochem.yunlian.upm.admin.constant.UserRoleSourceType"]>
>>>>>>> 0bd0165f9ee17b8cf36b8a30d1fb0c3beb3c9a16
