<div class="navbar navbar-inverse navbar-static-top">
    <div class="navbar-inner">
        <span class="brand" >权限管理系统</span>
        <ul class="nav pull-right">
            <li class="divider"></li>
            <li><a href="/">首页</a></li>
            <li class="divider"></li>
            <li><a href="/help">帮助</a></li>
            <li class="divider"></li>
            <li class="has-form">
                <a class="button" href="/login">登陆</a>
            </li>
        </ul>
    </div>
</div>
